version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - ./data/db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
